name: CI

on:
  push:
    branches: [main, feat/*]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Check bundle size (Composer)
        run: |
          if [ -f "apps/composer/dist/assets/*.js" ]; then
            SIZE=$(gzip -c apps/composer/dist/assets/*.js | wc -c)
            MAX_SIZE=$((150 * 1024))  # 150 KB
            if [ $SIZE -gt $MAX_SIZE ]; then
              echo "Bundle size $SIZE exceeds limit $MAX_SIZE"
              exit 1
            fi
            echo "Bundle size: $SIZE bytes (under 150 KB limit)"
          fi
